### ISSUE TITLE
Gulpfile is empty

### ISSUE THREAD

**Issue by daannijkamp** [addthis/fluxthis.io#2]
Is there a reason that the gulpfile is empty?

-Daan

**Comment by jhorwit2** [comment]
Accidental lazyness.

I meant to automate the build when i created the docs page, but forgot due to working on fluxthis features.

Good catch :). 

Ill add a build/watch task shortly.

**Comment by jhorwit2** [comment]
As of right now we really don't need a gulp file. We just use webpack / webpack dev server. I'm going to remove the file and close this.
