### ISSUE TITLE
npm install failing with given dependencies

### ISSUE THREAD

**Issue by stevedumais** [addthis/fluxthis.io#9]
npm ERR! Darwin 14.3.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package phantomjs does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer mocha-phantomjs@3.6.0 wants phantomjs@1.9.1 - 1.9.7-15

**Comment by jhorwit2** [comment]
Hey steve,

Did you create this ticket on the right repo? Our docs repo doesn't use those packages.

**Comment by jhorwit2** [comment]
Mind moving this over to https://github.com/addthis/fluxthis

**Comment by jhorwit2** [comment]
random note, I tried doing npm install on both projects and nothing broke. I even `rm -rf node_modules` and cleared npm cache.

**Comment by stevedumais** [comment]
Yeah.... too many tabs - I actually copied `git clone https://github.com/mako-taco/react-fluxthis-webpack-mocha-gulp.git` off of fluxthis.io, and ran the npm install, which broke.
